# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dist_PBAL <- function(d) {
    .Call('_REpiclomal_dist_PBAL', PACKAGE = 'REpiclomal', d)
}

.impute_means <- function(input_data) {
    .Call('_REpiclomal_impute_means', PACKAGE = 'REpiclomal', input_data)
}

.impute_medians <- function(input_data) {
    .Call('_REpiclomal_impute_medians', PACKAGE = 'REpiclomal', input_data)
}

.find_variable_region <- function(r, cluster_set, estimate_epi, rstart, rend) {
    .Call('_REpiclomal_find_variable_region', PACKAGE = 'REpiclomal', r, cluster_set, estimate_epi, rstart, rend)
}

.impute_missing_data <- function(meth_data, data_estimate_corr, estimate_Z, rstart, rend, variable_region) {
    invisible(.Call('_REpiclomal_impute_missing_data', PACKAGE = 'REpiclomal', meth_data, data_estimate_corr, estimate_Z, rstart, rend, variable_region))
}

