// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dist_PBAL
NumericMatrix dist_PBAL(NumericMatrix d);
RcppExport SEXP _epiclomal_npm_cluster_dist_PBAL(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_PBAL(d));
    return rcpp_result_gen;
END_RCPP
}
// impute_means
NumericMatrix impute_means(NumericMatrix input_data);
RcppExport SEXP _epiclomal_npm_cluster_impute_means(SEXP input_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_data(input_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_means(input_data));
    return rcpp_result_gen;
END_RCPP
}
// impute_medians
IntegerMatrix impute_medians(IntegerMatrix input_data);
RcppExport SEXP _epiclomal_npm_cluster_impute_medians(SEXP input_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type input_data(input_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_medians(input_data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_epiclomal_npm_cluster_dist_PBAL", (DL_FUNC) &_epiclomal_npm_cluster_dist_PBAL, 1},
    {"_epiclomal_npm_cluster_impute_means", (DL_FUNC) &_epiclomal_npm_cluster_impute_means, 1},
    {"_epiclomal_npm_cluster_impute_medians", (DL_FUNC) &_epiclomal_npm_cluster_impute_medians, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_epiclomal_npm_cluster(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
